package com.test;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.test.apolloAndroid.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testTestRegister() {
        Library classUnderTest = new Library();
        assertTrue("testRegister should return 'true'", classUnderTest.testRegister());
    }
}
